### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by warmachinesocial** [holepunchto/bare-expo#3]
I was trying to use hyperswarm but got error on sodium-native required, installed in but still didn't work

Error- > Please try again later.
bareexpo.app/Frameworks/sodium-native.4.2.0.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "bareexpo.app/Frameworks/sodium-native.4.2.0.framework/sodium-native-4.2.0".

**Comment by kasperisager** [comment]
Fixed in https://github.com/holepunchto/react-native-bare-kit/commit/8fe86ad01928353ec22751c7dc3d0343e3b1fb70. cb34bc299d567e02963d6dee0cc6a9b5ed8eb900 updates `react-native-bare-kit` to latest.
